version: "3.1"

services:
  mongodb:
    image : mongo:4.2.15-bionic
    container_name: mongodb
    restart: always
    volumes:
      - ./database:/data/db
      - ./data_load:/data_load
    environment:
      MONGO_INITDB_ROOT_USERNAME:  ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD:  ${DB_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - services-net
networks:
  services-net:
